Repository opengento/magento2-gdpr, pull requests merged in 2020-12, with the labels that each got.

#59 #55 add german translation
  i18n/de_DE.csv
Labels: enhancement

#67 Translate /i18n/en_US.csv in nl_NL
  i18n/nl_NL.csv
Labels: enhancement

#70 Fix Error 500 in customer account on Magento 2.3 bug #48
  Controller/AbstractPrivacy.php
Labels: bug

#71 Magento2.3.x compatibility
  Controller/Privacy/Erase.php
  Controller/Privacy/UndoErase.php
  Model/Config/PrivacyMessage.php
  view/frontend/layout/customer_account.xml
Labels: bug, enhancement
